### ISSUE TITLE
Always get a https://localhost/4321 domain when I deploy the app

### ISSUE THREAD

**Issue by pankajsurti** [estruyf/UploadToOffice365SPFx#1]
Should not this be something like "https://publiccdn.sharepointonline.com/<my tenant>.sharepoint.com/sites/CDN/CDN/newIdea/" as defined in the write-manifests.json?

![image](https://user-images.githubusercontent.com/108044/36312732-16ec8a1c-12f5-11e8-801c-9ff4baecf7e2.png)

**Comment by estruyf** [comment]
Did you do `gulp package-solution --ship`? Because if you don't use the `--ship` flag, it will use the debug build which references your localhost.
